- name: Copy deployment configuration
  copy:
    src: "{{ ENVIRONMENT_TAG }}-deployment.yaml"
    dest: $HOME

- name: Apply deployment configuration
  shell: "./bin/kubectl apply -f {{ ENVIRONMENT_TAG }}-deployment.yaml"
  args:
    chdir: $HOME