- name: Copy service configuration
  copy:
    src: "{{ ENVIRONMENT_TAG }}-service.yaml"
    dest: $HOME

- name: Create service configuration
  command: "./bin/kubectl apply -f {{ ENVIRONMENT_TAG }}-service.yaml"
  args:
    chdir: $HOME