apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-deployment
  labels:
    app: udacity-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: udacity-app
  template:
    metadata:
      labels:
        app: udacity-app
    spec:
      terminationGracePeriodSeconds: 30    
      containers:
        - name: udacity-app
          image: roshini777/capstonetest:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80